# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           date
relative_permalinks: true

# Setup
title:               常春藤的博客
tagline:             ''
description:         ''
url:                 http://zyfa.info
baseurl:             'http://zyfa.info'
paginate:            5

# About/contact
author:
  name:              Thomas
  url:               http://zyfa.info
  email:             zyfa2008@gmail.com

# Custom vars
version:             1.0.0
